### ISSUE TITLE
MeasureBasedCounter does not exist

### ISSUE THREAD

**Issue by hasn-ab** [quickpose/quickpose-ios-sdk#6]
Hi @pablonosh, 
I am getting the following error after integrating the SDK with Cocoapods. 
    
<img width="1075" alt="Screenshot 2023-06-10 at 2 19 54 AM" src="https://github.com/quickpose/quickpose-ios-sdk/assets/67307736/ac0513d7-7065-4cf7-a70d-610afc9347af">

It looks like this was removed, as I could not find it in the `QuickPoseCore` module.

**Comment by dvolkhonskiy** [comment]
Hi @hasn-ab!

Now you can use QuickPoseThresholdCounter instead of MeasureBasedCounter. Internally they provide the same functionality, so we removed one of them. Feel free to play with enterThreshold and exitThreshold parameters (0.6 and 0.3 by default) to adjust the sensitivity. 

MeasureBasedTimer was replaced by QuickPoseThresholdTimer with the same functionality and slightly different methods.

Let me know if you have any further questions.

**Comment by dvolkhonskiy** [comment]
Here are a couple of examples of how you can use them:

https://docs.quickpose.ai/docs/MobileSDK/Features/Exercises/Plank#plank-timing Timer
https://docs.quickpose.ai/docs/MobileSDK/Features/Exercises/Bicep%20Curls#bicep-curl-counting Counter
