### ISSUE TITLE
Unsigned Framework

### ISSUE THREAD

**Issue by xiaobaishu0097** [quickpose/quickpose-ios-sdk#9]
Thanks for your excellent works!

I am trying to build a demo following the instructions in a [YouTube video](https://www.youtube.com/watch?v=6BsqfXPLdRM&t=309s). However, when I built the project following his guidance in [4:49](https://youtu.be/6BsqfXPLdRM?t=289), I got a building failed error message. One of the error messages in my Xcode is "The Framework “QuickPoseCore.xcframework” is unsigned. Xcode will be unable to verify if the author changes.". 
There is no response for selecting the "Accept Unsigned" button. 

Could anyone please help me on this matter?

Thanks!

**Comment by pablonosh** [comment]
Hi xiaobaishu0097

I believe a member of the team has reached out to you directly. 

If in doubt please base projects on our simpler sample apps rather than the deep dive videos as these are hard for us to maintain as we extend the SDK and would need to keep re-shooting videos for the deep dives.

I'll close this ticket now but do get in touch if you have any further issues.
